server:
  port: 4003
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: mybatis-plus2020
  profiles:
    active: multidatasource
#    active: singledatasource


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      #驼峰下划线转换
      #column-underline: true
      #逻辑删除配置
      logic-delete-value: I
      logic-not-delete-value: A
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #为所有Entity类所在包起默认别名
  type-aliases-package: com.chris.mybatisplus.entities

logging:
  level:
    # 根日志级别
    root: info
    # 数据查询接口级别
    com.chris.mybatisplus.dao.mapper: debug


helloworld:
  chris:
    prefix: My name is
    suffix: Say hello to the world!



async:
  executor:
    thread:
      core_pool_size: 5      #配置核心线程数
      max_pool_size: 5       # 配置最大线程数
      queue_capacity: 99999  # 配置队列大小
      name_prefix: async-service- # 配置线程池中的线程的名称前缀